### ISSUE TITLE
aiida-core distribution not found

### ISSUE THREAD

**Issue by ltalirz** [DropD/aiida-mul#2]
After having installed the plugin, set up the code & computer, I still get an error when trying to submit a calculation:

```error
  File "/Users/leopold/Applications/miniconda3/envs/aiida_pawel2/lib/python2.7/site-packages/reentry/jsonbackend.py", line 174, in get_map
    raise ValueError("The {} distribution was not found.".format(dist))
ValueError: The aiida-core distribution was not found.
```

The error arises from the line
```
calc = code.new_calc()
```
in the submission script.

Full traceback below.

```
$ verdi run examples/cli.py aiida_mul localhost
Traceback (most recent call last):
  File "/Users/leopold/Applications/miniconda3/envs/aiida_pawel2/bin/verdi", line 11, in <module>
    sys.exit(run())
  File "/Users/leopold/Applications/miniconda3/envs/aiida_pawel2/lib/python2.7/site-packages/aiida/cmdline/verdilib.py", line 1216, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_pawel2/lib/python2.7/site-packages/aiida/cmdline/verdilib.py", line 1201, in exec_from_cmdline
    CommandClass.run(*argv[command_position + 1:])
  File "/Users/leopold/Applications/miniconda3/envs/aiida_pawel2/lib/python2.7/site-packages/aiida/cmdline/verdilib.py", line 1065, in run
    exec (f, globals_dict)
  File "examples/cli.py", line 54, in <module>
    main()
  File "/Users/leopold/Applications/miniconda3/envs/aiida_pawel2/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_pawel2/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_pawel2/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_pawel2/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "examples/cli.py", line 31, in main
    calc = code.new_calc()
  File "/Users/leopold/Applications/miniconda3/envs/aiida_pawel2/lib/python2.7/site-packages/aiida/orm/implementation/general/code.py", line 425, in new_calc
    C = CalculationFactory(plugin_name)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_pawel2/lib/python2.7/site-packages/aiida/orm/utils.py", line 32, in CalculationFactory
    suffix="Calculation")
  File "/Users/leopold/Applications/miniconda3/envs/aiida_pawel2/lib/python2.7/site-packages/aiida/common/pluginloader.py", line 182, in BaseFactory
    return get_plugin(category, module)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_pawel2/lib/python2.7/site-packages/aiida/common/pluginloader.py", line 124, in get_plugin
    plugin = entrypoint.load()
  File "/Users/leopold/Applications/miniconda3/envs/aiida_pawel2/lib/python2.7/site-packages/reentry/entrypoint.py", line 36, in load
    module = import_module(self.module_name)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_pawel2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/leopold/Personal/Postdoc-MARVEL/Projects/2017-09-15_pawel_plugin/aiida-mul/aiida_mul/calcs.py", line 12, in <module>
    class MultiplyCalculation(JobCalculation):
  File "/Users/leopold/Applications/miniconda3/envs/aiida_pawel2/lib/python2.7/site-packages/aiida/orm/implementation/general/node.py", line 122, in __new__
    if entry_point_tpstr_from(classname):
  File "/Users/leopold/Applications/miniconda3/envs/aiida_pawel2/lib/python2.7/site-packages/aiida/common/pluginloader.py", line 245, in entry_point_tpstr_from
    mapping = get_class_to_entry_point_map(short_group_name=True).get(class_path)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_pawel2/lib/python2.7/site-packages/aiida/common/pluginloader.py", line 217, in get_class_to_entry_point_map
    groups = (g for g in epm.get_entry_map('aiida-core').iterkeys() if g.startswith('aiida'))
  File "/Users/leopold/Applications/miniconda3/envs/aiida_pawel2/lib/python2.7/site-packages/reentry/manager.py", line 29, in get_entry_map
    return bkend.get_map(dist=distname, group=group)
  File "/Users/leopold/Applications/miniconda3/envs/aiida_pawel2/lib/python2.7/site-packages/reentry/jsonbackend.py", line 174, in get_map
    raise ValueError("The {} distribution was not found.".format(dist))
ValueError: The aiida-core distribution was not found.
```

**Comment by ltalirz** [comment]
copied over (from @DropD)
This is due to aiidateam/aiida_core#632. Until that is fixed in a release it is necessary to run reentry scan aiida after installing aiida in a new virtualenv.

**Comment by DropD** [comment]
... or probably `reentry scan -r aiida`

**Comment by ltalirz** [comment]
Great, it works now. Let's leave the issue open for the moment in order to remember to remove `reentry scan -r aiida` once it's no longer required

**Comment by ltalirz** [comment]
We're no longer maintaining aiida-mul.
Have a look at https://github.com/aiidateam/aiida-diff instead.
